name: Hello World Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display Hello World
        run: |
          echo "Hello, World! This is my first GitHub Action."
